package palsettings

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

const sampleINI = `; This configuration file is a sample of the default server settings.
; Changes to this setting will not be able to be reflected on the server.

[/Script/Engine.GameSession]
MaxPlayers=32
OptionSettings=(Fake=Before)

[/Script/Pal.PalGameWorldSettings]
OptionSettings=(Difficulty=None,ExpRate=1.000000,ServerName="Pal Test=1",ServerPassword="a,b",DeathPenalty=Item)
`

func TestParseINI(t *testing.T) {
	m, err := ParseINI(sampleINI)
	if err != nil {
		t.Fatalf("ParseINI: %v", err)
	}
	want := map[string]string{
		"Difficulty":     "None",
		"ExpRate":        "1.000000",
		"ServerName":     "Pal Test=1",
		"ServerPassword": "a,b",
		"DeathPenalty":   "Item",
	}
	for k, v := range want {
		if m[k] != v {
			t.Fatalf("ParseINI[%q] = %q, 期望 %q", k, m[k], v)
		}
	}
	if _, ok := m["Fake"]; ok {
		t.Fatal("段外 OptionSettings 不应被采集")
	}
	if _, ok := m["MaxPlayers"]; ok {
		t.Fatal("其他段键不应被采集")
	}
}

func TestParseINIEscapedQuote(t *testing.T) {
	m, err := ParseINI(`[/Script/Pal.PalGameWorldSettings]
OptionSettings=(ServerPassword="a""b",ServerName="")
`)
	if err != nil {
		t.Fatalf("ParseINI: %v", err)
	}
	if m["ServerPassword"] != `a"b` {
		t.Fatalf("ServerPassword = %q, 期望 %q", m["ServerPassword"], `a"b`)
	}
	if m["ServerName"] != "" {
		t.Fatalf("ServerName = %q, 期望空串", m["ServerName"])
	}
}

func TestParseINIMissingSectionOrOption(t *testing.T) {
	if _, err := ParseINI("[Foo]\nBar=1\n"); err == nil {
		t.Fatal("缺段应报错")
	}
	if _, err := ParseINI("[/Script/Pal.PalGameWorldSettings]\nFoo=1\n"); err == nil {
		t.Fatal("缺 OptionSettings 应报错")
	}
}

// I1：实机 ini 的括号列表值为未加引号形态，ParseINI 必须整段识别为单值，
// 否则被引号切分截断为 "(Steam"，下次 PUT 固化为脏数据。
func TestParseINIParenListValue(t *testing.T) {
	m, err := ParseINI(`[/Script/Pal.PalGameWorldSettings]
OptionSettings=(Difficulty=None,CrossplayPlatforms=(Steam,Xbox,PS5,Mac),ServerName="Pal Test")
`)
	if err != nil {
		t.Fatalf("ParseINI: %v", err)
	}
	if m["CrossplayPlatforms"] != "(Steam,Xbox,PS5,Mac)" {
		t.Fatalf("括号列表值应整段保留: %q", m["CrossplayPlatforms"])
	}
	if m["ServerName"] != "Pal Test" {
		t.Fatalf("后续键不应受影响: %q", m["ServerName"])
	}
}

// I1：实机形态 parse→serialize→parse 往返，键值逐字节一致（含引号字符串内的 =( 形态）。
func TestParenListRoundTripRealMachine(t *testing.T) {
	content := `; header
[/Script/Pal.PalGameWorldSettings]
OptionSettings=(Difficulty=None,CrossplayPlatforms=(Steam,Xbox,PS5,Mac),ServerName="a=(b,c)",BanListURL="https://x/y")
`
	m1, err := ParseINI(content)
	if err != nil {
		t.Fatalf("ParseINI: %v", err)
	}
	line := Serialize(nil, m1)
	full := "; Generated by PalPanel\n[/Script/Pal.PalGameWorldSettings]\n" + line + "\n"
	m2, err := ParseINI(full)
	if err != nil {
		t.Fatalf("二次 ParseINI: %v\n%s", err, line)
	}
	// Serialize(nil, m1) 会补全全部 schema 键，m2 ⊇ m1：逐键比对 m1 即可
	for k, v := range m1 {
		if m2[k] != v {
			t.Fatalf("往返不一致 [%q]: %q vs %q", k, v, m2[k])
		}
	}
	if m2["CrossplayPlatforms"] != "(Steam,Xbox,PS5,Mac)" {
		t.Fatalf("括号列表值往返后应完整: %q", m2["CrossplayPlatforms"])
	}
}

func TestSerializeOrderAndPreserve(t *testing.T) {
	overrides := map[string]string{"ExpRate": "2.5", "ServerName": "Pal Panel"}
	existing := map[string]string{
		"Difficulty": "Difficulty",
		"Zeta":       "z",
		"Alpha":      "a",
	}
	got := Serialize(overrides, existing)
	// 全量 schema 下输出含所有键，这里按相对顺序与关键片段断言
	iDiff := strings.Index(got, "Difficulty=Difficulty")
	iExp := strings.Index(got, "ExpRate=2.500000")
	iName := strings.Index(got, "ServerName=Pal Panel")
	iAlpha := strings.Index(got, ",Alpha=a")
	iZeta := strings.Index(got, ",Zeta=z")
	if iDiff < 0 || iExp < 0 || iName < 0 || iAlpha < 0 || iZeta < 0 {
		t.Fatalf("Serialize 缺少关键片段: %s", got)
	}
	// schema 键按 fields.json 序，未管理键按字母序追加在末尾
	if !(iDiff < iExp && iExp < iName && iName < iAlpha && iAlpha < iZeta) {
		t.Fatalf("Serialize 键序不符: %s", got)
	}
	// 除两个未管理键外不应再有等号后内容跟在 Zeta 之后
	if tail := got[iZeta:]; tail != ",Zeta=z)" {
		t.Fatalf("未管理键应在末尾: %q", tail)
	}
}

func TestSerializeEmptyOverrideFallsBack(t *testing.T) {
	// 空 override 视为未设置，回退 existing → Default（取实机 ini 默认值）
	got := Serialize(map[string]string{"ServerName": ""}, map[string]string{})
	m, err := ParseINI("; h\n[/Script/Pal.PalGameWorldSettings]\n" + got + "\n")
	if err != nil {
		t.Fatalf("ParseINI: %v", err)
	}
	if m["ServerName"] != "Default Palworld Server" {
		t.Fatalf("空 override 应回退到实机默认值: %q", m["ServerName"])
	}
	if m["ServerPassword"] != "" {
		// 实机默认即为空串的键，回退后仍为空
		t.Fatalf("ServerPassword 应回退到空串默认: %q", m["ServerPassword"])
	}
	if m["Difficulty"] != "None" || m["ExpRate"] != "1.000000" {
		t.Fatalf("应回退到 schema Default: %q/%q", m["Difficulty"], m["ExpRate"])
	}
}

func TestSerializeQuoteEscapeRoundTrip(t *testing.T) {
	v := `a"b,c=d`
	line := Serialize(map[string]string{"ServerName": v}, nil)
	if !strings.Contains(line, `ServerName="a""b,c=d"`) {
		t.Fatalf("应加引号并转义: %s", line)
	}
	full := "; header\n[/Script/Pal.PalGameWorldSettings]\n" + line + "\n"
	m, err := ParseINI(full)
	if err != nil {
		t.Fatalf("ParseINI: %v", err)
	}
	if m["ServerName"] != v {
		t.Fatalf("往返不一致: %q vs %q", m["ServerName"], v)
	}
}

func TestSerializeParseRoundTripQuoteEdge(t *testing.T) {
	cases := []string{
		`pass""word`, // 连续双引号
		`"`,          // 恰为单个引号
		`"a"`,        // 两端引号
		`a"b,c=d`,    // 引号+逗号+等号混合
		`a,b`,        // 纯逗号
	}
	for _, v := range cases {
		line := Serialize(map[string]string{"ServerName": v}, nil)
		full := "; h\n[/Script/Pal.PalGameWorldSettings]\n" + line + "\n"
		m, err := ParseINI(full)
		if err != nil {
			t.Fatalf("ParseINI(%q): %v", line, err)
		}
		if m["ServerName"] != v {
			t.Fatalf("往返不一致: 原值 %q, 序列化 %q, 解析回 %q", v, line, m["ServerName"])
		}
	}
}

func TestFormatValueBoolAndFloat(t *testing.T) {
	if got := formatValue(Field{Key: "b", Type: "bool"}, "true"); got != "True" {
		t.Fatalf("bool true → %q, 期望 True", got)
	}
	if got := formatValue(Field{Key: "b", Type: "bool"}, "FALSE"); got != "False" {
		t.Fatalf("bool FALSE → %q, 期望 False", got)
	}
	if got := formatValue(Field{Key: "f", Type: "float"}, "2.5"); got != "2.500000" {
		t.Fatalf("float → %q, 期望 2.500000", got)
	}
}

func TestValidateValueWithSchemaField(t *testing.T) {
	// fields.json 中的 ExpRate 走 schema 校验路径（全量生成后无 Min/Max 限制）
	f, _ := FieldByKey("ExpRate")
	if err := Validate(f, "1.5"); err != nil {
		t.Fatalf("ExpRate=1.5 应合法: %v", err)
	}
	if err := Validate(f, "0"); err != nil {
		t.Fatalf("无 Min 限制时 ExpRate=0 应合法: %v", err)
	}
	if err := Validate(f, "abc"); err == nil {
		t.Fatal("ExpRate=abc 应报非数值错误")
	}
	// string 类型键：长度限制生效
	fs, _ := FieldByKey("ServerName")
	if err := Validate(fs, strings.Repeat("测", 129)); err == nil {
		t.Fatal("ServerName 129 字符应报超长错误")
	}
}

const iniFileContent = "; header\n[/Script/Pal.PalGameWorldSettings]\nOptionSettings=(Difficulty=None,ExpRate=1.500000,ServerName=Panel)\n"

// C1：SaveGameINI 对裸 OptionSettings 行必须补全为完整合法 ini
//（注释 + 段头 + OptionSettings 行），否则 PalServer 不应用、下次读取报缺段。
func TestSaveGameINIWritesCompleteINI(t *testing.T) {
	dir := t.TempDir()
	line := Serialize(map[string]string{"ExpRate": "2.0"}, nil)
	if err := SaveGameINI(dir, line); err != nil {
		t.Fatalf("SaveGameINI: %v", err)
	}
	p := GameINIPath(dir)
	b, err := os.ReadFile(p)
	if err != nil {
		t.Fatal(err)
	}
	content := string(b)
	if !strings.HasPrefix(content, "; Generated by PalPanel\n") {
		t.Fatalf("首行应为生成注释: %q", content)
	}
	if !strings.Contains(content, sectionHeader+"\n"+line) {
		t.Fatalf("应为 段头+OptionSettings 行 结构: %q", content)
	}
	// 引擎级往返：Save → Load 不报错且值一致
	m, err := LoadGameINI(dir)
	if err != nil {
		t.Fatalf("LoadGameINI(保存后的 ini) 不应报缺段: %v", err)
	}
	if m["ExpRate"] != "2.000000" {
		t.Fatalf("往返值不符: %v", m)
	}
}

func TestSaveLoadGameINIRoundTrip(t *testing.T) {
	dir := t.TempDir()
	if err := SaveGameINI(dir, iniFileContent); err != nil {
		t.Fatalf("SaveGameINI: %v", err)
	}
	m, err := LoadGameINI(dir)
	if err != nil {
		t.Fatalf("LoadGameINI: %v", err)
	}
	if m["ExpRate"] != "1.500000" || m["ServerName"] != "Panel" {
		t.Fatalf("往返结果不符: %v", m)
	}
	// 文件确实落在平台子目录
	platform := "LinuxServer"
	if filepath.Separator == '\\' {
		platform = "WindowsServer"
	}
	p := filepath.Join(dir, "Pal", "Saved", "Config", platform, "PalWorldSettings.ini")
	if _, err := os.Stat(p); err != nil {
		t.Fatalf("期望文件 %s: %v", p, err)
	}
}

func TestLoadGameININotExist(t *testing.T) {
	m, err := LoadGameINI(t.TempDir())
	if err != nil {
		t.Fatalf("文件不存在应返回 nil 错误: %v", err)
	}
	if len(m) != 0 {
		t.Fatalf("应返回空 map, got %v", m)
	}
}

func TestWorldOptionHint(t *testing.T) {
	dir := t.TempDir()
	old := time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC)
	past := time.Date(2025, 1, 1, 0, 0, 0, 0, time.UTC)
	future := time.Date(2027, 1, 1, 0, 0, 0, 0, time.UTC)

	// 无 WorldOption.sav → 空串
	if got := WorldOptionHint(dir, old); got != "" {
		t.Fatalf("无存档应返回空串, got %q", got)
	}

	sav := filepath.Join(dir, "Pal", "Saved", "SaveGames", "0", "ABC123", "WorldOption.sav")
	if err := os.MkdirAll(filepath.Dir(sav), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(sav, []byte("gvas"), 0o644); err != nil {
		t.Fatal(err)
	}

	// 存档比 ini 新 → 提示
	if got := WorldOptionHint(dir, past); got == "" {
		t.Fatal("存档更新时应返回提示")
	}
	// ini 比存档新 → 空串
	if got := WorldOptionHint(dir, future); got != "" {
		t.Fatalf("ini 更新时应返回空串, got %q", got)
	}
}
